### PR TITLE
Start adding TableCollection stuff

### PR DESCRIPTION
**Pull request by molpopgen**
WIP/thought experiment on a TskTableCollection rust struct.

cc @jeromekelleher

### CODE REVIEW

**Comment by jeromekelleher** [comment]
This looks really cool @molpopgen, I've had a quick scan without taking too much in. Please ping me if you'd like me to take a closer look at any point.

**Comment by molpopgen** [comment]
Will do!  This is evolving rather quickly.

**Comment by molpopgen** [comment]
@jeromekelleher  -- I think this is getting rather close.  If you have the time, the easiest thing may be:

1. Install rust:

```
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
```

2. Clone this repo and checkout `table_collection_wrapper`

3. `git submodule update --init --recursive`

4. `cargo doc --open` will point your browser at the docs, which contains a full source code browser!

**Comment by jeromekelleher** [comment]
Thanks @molpopgen, I'd love to try it out but the stack is a bit high at the moment. What's the timeframe you'd like to get feedback on this?

**Comment by molpopgen** [comment]
There's no pressure.  I may merge this so that my forward sim experiment can use it.  I figure this is alpha, so anything dumb isn't forever.

By the time you have time, maybe I'll have added in the other tables currently missing, etc..

**Comment by jeromekelleher** [comment]
OK, sounds good @molpopgen. I'm afraid I just can't justify playing around with this right now!

**Pull request merged**
